# Generated by Django 4.1.5 on 2023-01-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='self',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='self',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='self',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='self',
            name='skill4',
        ),
    ]
