# Generated by Django 4.1.5 on 2023-01-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_self_skill1_remove_self_skill2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(blank=True, max_length=15, null=True)),
                ('p2', models.CharField(blank=True, max_length=15, null=True)),
                ('p3', models.CharField(blank=True, max_length=15, null=True)),
                ('p4', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
