# Generated by Django 4.1.5 on 2023-01-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_postion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postion',
            new_name='Position',
        ),
    ]
