# Generated by Django 4.1.5 on 2023-01-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_postion_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='self',
            name='p1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='self',
            name='p2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='self',
            name='p3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='self',
            name='p4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
