# Generated by Django 4.1.5 on 2023-01-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_position_self_p1_self_p2_self_p3_self_p4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='self',
            old_name='p1',
            new_name='position1',
        ),
        migrations.RenameField(
            model_name='self',
            old_name='p2',
            new_name='position2',
        ),
        migrations.RenameField(
            model_name='self',
            old_name='p3',
            new_name='position3',
        ),
        migrations.RenameField(
            model_name='self',
            old_name='p4',
            new_name='position4',
        ),
    ]
