# Generated by Django 4.1.5 on 2023-01-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_p1_self_position1_rename_p2_self_position2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self',
            name='position1',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='position2',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='position3',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='position4',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
