# Generated by Django 4.1.5 on 2023-01-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_self_position1_alter_self_position2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self',
            name='position1',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='position2',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='position3',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='position4',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
