# Generated by Django 4.1.5 on 2023-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_self_position1_alter_self_position2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('Website', models.URLField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, max_length=3, null=True)),
                ('Degree', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20, null=True)),
                ('desc', models.TextField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
