# Generated by Django 4.1.5 on 2023-01-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=450, null=True)),
                ('skill1_t', models.CharField(blank=True, max_length=25, null=True)),
                ('skill1_v', models.IntegerField(blank=True, null=True)),
                ('skill2_t', models.CharField(blank=True, max_length=25, null=True)),
                ('skill2_v', models.IntegerField(blank=True, null=True)),
                ('skill3_t', models.CharField(blank=True, max_length=25, null=True)),
                ('skill3_v', models.IntegerField(blank=True, null=True)),
                ('skill4_t', models.CharField(blank=True, max_length=25, null=True)),
                ('skill4_v', models.IntegerField(blank=True, null=True)),
                ('skill5_t', models.CharField(blank=True, max_length=25, null=True)),
                ('skill5_v', models.IntegerField(blank=True, null=True)),
                ('skill6_t', models.CharField(blank=True, max_length=25, null=True)),
                ('skill6_v', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='introduction',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
