# Generated by Django 4.1.5 on 2023-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_skills_alter_about_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc1', models.TextField(blank=True, max_length=450, null=True)),
                ('desc2', models.TextField(blank=True, max_length=450, null=True)),
                ('desc3', models.TextField(blank=True, max_length=450, null=True)),
                ('desc4', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc1', models.TextField(blank=True, max_length=450, null=True)),
                ('desc2', models.TextField(blank=True, max_length=450, null=True)),
                ('desc3', models.TextField(blank=True, max_length=450, null=True)),
                ('desc4', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=450, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('adress', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
