# Generated by Django 4.1.5 on 2023-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_education_education2_experience_experience2_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education2',
        ),
        migrations.DeleteModel(
            name='Experience2',
        ),
        migrations.AddField(
            model_name='education',
            name='desc1',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='period1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='place1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc5',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc6',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc7',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc8',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='period1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='place1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
