# Generated by Django 4.1.5 on 2023-01-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_education2_delete_experience2_education_desc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('period1', models.CharField(blank=True, max_length=20, null=True)),
                ('place1', models.CharField(blank=True, max_length=50, null=True)),
                ('desc1', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc1', models.TextField(blank=True, max_length=450, null=True)),
                ('desc2', models.TextField(blank=True, max_length=450, null=True)),
                ('desc3', models.TextField(blank=True, max_length=450, null=True)),
                ('desc4', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('desc1', models.TextField(blank=True, max_length=450, null=True)),
                ('desc2', models.TextField(blank=True, max_length=450, null=True)),
                ('desc3', models.TextField(blank=True, max_length=450, null=True)),
                ('desc4', models.TextField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='main_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
