# Generated by Django 4.1.5 on 2023-01-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_resume1_resume2_resume3_resume4_delete_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume2',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='resume2',
            old_name='period1',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='resume2',
            old_name='place1',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='resume2',
            old_name='title1',
            new_name='title',
        ),
    ]
