# Generated by Django 4.1.5 on 2023-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_rename_desc1_resume2_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_desc', models.TextField(blank=True, max_length=450, null=True)),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('desc1', models.TextField(blank=True, max_length=300, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('desc2', models.TextField(blank=True, max_length=300, null=True)),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('desc3', models.TextField(blank=True, max_length=300, null=True)),
                ('title4', models.CharField(blank=True, max_length=50, null=True)),
                ('desc4', models.TextField(blank=True, max_length=300, null=True)),
                ('title5', models.CharField(blank=True, max_length=50, null=True)),
                ('desc5', models.TextField(blank=True, max_length=300, null=True)),
                ('title6', models.CharField(blank=True, max_length=50, null=True)),
                ('desc6', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
