# Generated by Django 4.1.5 on 2023-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_skills_skill6_t_alter_skills_skill6_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill6_t',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill6_v',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
