# Generated by Django 4.1.5 on 2023-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_skills_skill6_t_alter_skills_skill6_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='about/0.png', upload_to='about/'),
        ),
    ]
