# Generated by Django 4.1.5 on 2023-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self',
            name='image',
            field=models.ImageField(default='about/0.png', upload_to='profile/'),
        ),
    ]
